version: "3.7"

services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db-social-networking
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
