import Head from "next/head";
import Image from "next/image";
import React, { useState } from 'react';
import { api } from "~/utils/api";



export default function Home() {

return (

<>

    <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="mx-auto my-auto">
        <div className="w-[390px] h-[844px] relative bg-neutral-700"
            style={{ backgroundImage: 'url("images/bg1.png")', backgroundSize: 'cover', backgroundPosition: 'center' }}>
            <div className=" left-0 top-0 absolute">

                <img className="w-[390px] h-[845px] left-[-6px] top-[-189px] absolute" src={"images/bg1.png"} />
            </div>
            <div
                className="w-[390px] pl-[129px] pr-32 py-3.5 left-0 top-0 absolute bg-neutral-300 bg-opacity-50 backdrop-blur-sm justify-center items-center inline-flex">
                <div
                    className="px-12 pt-2 pb-3 bg-zinc-800 bg-opacity-40 rounded-[9px] justify-center items-center inline-flex">
                    <div className="text-white text-base font-normal font-['Be Vietnam'] leading-[18px]">Criar</div>
                </div>
            </div>
            <div className="w-[368px] h-[156.05px] left-[11px] top-[160px] absolute">
                <div
                    className="w-[368px] h-[206px] py-[22px]  absolute bg-white rounded-[26px] flex-col justify-center items-center gap-3.5 inline-flex">
                    <textarea
    className="w-full h-full px-2 py-2 text-zinc-800 text-opacity-70 text-xs font-normal font-['Be Vietnam'] leading-[18px] resize-none"
    placeholder="Digite aqui o que você deseja publicar"
  />
                    <div className="self-stretch justify-center items-center inline-flex">
                <button className="w-8 h-8 relative" style={{ backgroundImage: 'url("icons/coment.svg")', backgroundSize: 'cover', backgroundPosition: 'center' }}></button>
            </div>
        </div>
    </div>
    <div className="left-[34px] top-[76px] absolute justify-center items-center gap-[13px] inline-flex">
        <img className="w-[70px] h-[70px] rounded-[26px]" src={"images/perfil.png"} />
        <div className="flex-col justify-center items-start inline-flex">
            <div className="text-white text-base font-bold font-['Be Vietnam'] uppercase">Hannah Smith ( Você )</div>
            <div className="text-zinc-500 text-xs font-normal font-['Be Vietnam'] leading-[18px]">@hannah_super</div>
        </div>
    </div>
    <div className="w-[390px] h-[105px] left-0 top-[739px] absolute">
        <div className="w-[390px] h-[105px] left-0 top-0 absolute bg-neutral-700 bg-opacity-90 backdrop-blur-sm"></div>
        <div className="w-[274px] px-[7px] py-[8.50px] left-[58px] top-[12px] absolute justify-center items-center inline-flex">
            <div className="grow shrink basis-0 self-stretch justify-start items-start gap-[5px] inline-flex">
            <button
                            className="px-7 pt-2 pb-3 bg-white rounded-[9px] shadow flex-col justify-center items-center gap-[3px] flex group bg-cover group-hover:bg-blue-400 group-active:bg-blue-400 ">
                            <img className="w-[30px] h-[30px]" src={"/icons/feed.svg"} />
                            <div className="text-blue-400 text-[10px] font-normal font-['Be Vietnam'] leading-[18px]">
                                Feed</div>
                        </button>

                        <button
                            className="px-7 pt-2 pb-3 bg-white rounded-[9px] backdrop-blur-sm flex-col justify-center items-center gap-[3px] flex group">
                            <img className="w-[30px] h-[30px]" src={"/icons/criar.svg"} />
                            <div className="text-blue-400 text-xs font-normal font-['Be Vietnam'] leading-[18px]">Criar
                            </div>
                        </button>
                        <button
                            className="px-7 pt-2 pb-3 bg-white rounded-[9px] backdrop-blur-sm flex-col justify-center items-center gap-[3px] flex group">
                            <img className="w-[30px] h-[30px]" src={"/icons/perfil.svg"} />
                            <div className="text-blue-400 text-xs font-normal font-['Be Vietnam'] leading-[18px]">Perfil
                            </div>
                        </button>
            </div>
        </div>
    </div>
</div>
    </main>

</>
);
}