import Head from "next/head";
import Image from "next/image";


export default function Home() {
return (
<>

    <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="bg-main flex h-screen w-screen items-center justify-center bg-cover bg-no-repeat">
        <div className="flex justify-center">
            <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">
                Feed
            </button>
            <button className="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-full">
                Criar
            </button>
            <button className="bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full">
                Perfil
            </button>
        </div>

    </main>
</>
);
}