import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-main flex h-screen w-screen items-center justify-center">
        <div className="flex flex-col rounded-xl bg-white px-24 py-12">
          <Image
            alt="Logomarca"
            src={"/icons/logo.svg"}
            height={120}
            width={120}
          />

          <input
            type="text"
            placeholder="Digite o seu email"
            className="w-full"
          />
          <input
            type="password"
            placeholder="Digite a sua senha"
            className="w-full"
          />

          <button className="items-center justify-center rounded-xl px-12 py-8">
            Entrar
          </button>

          <p>
            Não possui conta? <a href="#">Registre-se</a>
          </p>
        </div>
      </main>
    </>
  );
}
